### ISSUE TITLE
Wrong check in "MoM: Upper east ledge"

### ISSUE THREAD

**Issue by SteveBass7** [sassyvania/Blasphemous-Randomizer-Maptracker#1]
This check doesn't require "blood", you can jump to get it.

https://github.com/sassyvania/Blasphemous-Randomizer-Maptracker/blob/1b6cee6b680454c5e41d43a09f5750cac2c1c1e4/locations/locations.json#L4920-L4921

**Comment by sassyvania** [comment]
got it, thanks!
